# Generated by Django 3.2.7 on 2021-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library_id',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
