# Generated by Django 3.2.7 on 2021-10-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('max_count', models.IntegerField()),
                ('current_count', models.IntegerField()),
            ],
        ),
    ]
